const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c=vm.createContext({});vm.runInContext(fs.readFileSync('src/main/resources/static/js/animalMap.js','utf8'),c);
const early={day:1,phase:'day',remaining:90},wolf={...early,remaining:60},night={day:1,phase:'night',remaining:110};
assert.equal(c.erHuntSpawned('Wolf',early),false,'no wolf at day 1 daytime 1:30');
assert.equal(c.erHuntSpawned('Bear',early),false,'bear first spawn is at night, not daytime 1:50');
assert.equal(c.erHuntSpawned('AttackDrone',early),false);
for(const type of ['Chicken','Bat','Boar','Dog'])assert(c.erHuntSpawned(type,early));
assert.equal(c.erHuntSpawned('Wolf',{...wolf,remaining:61}),false);
assert.equal(c.erHuntSpawned('Wolf',wolf),true,'countdown boundary is inclusive');
assert.equal(c.erHuntTime({...night,remaining:111}).remaining,110,'out-of-range countdown clamps to phase duration');
assert.equal(c.erHuntSpawned('Bear',night),true);
assert.equal(c.erHuntSpawned('AttackDrone',night),true);
assert.equal(c.erHuntSpawned('Wolf',night),false,'default assumes previous daytime wolf was killed');
assert.equal(c.erHuntSpawned('Wolf',{...night,survivors:true}),true,'survivor mode must not invent a nighttime despawn');
assert.equal(c.erHuntSpawned('Wolf',{day:2,phase:'day',remaining:140}),true);
assert.equal(c.erHuntSpawned('Bear',{day:2,phase:'day',remaining:140}),false);
assert.equal(c.erHuntSpawned('Bear',{day:2,phase:'night',remaining:120}),true);
const camps=['Chicken','Wolf','Bear','AttackDrone'].map((type,i)=>({id:type,type,region:'a',count:1,variant:0,x:i,y:i}));
let result=c.erRecommendHunt({x:0,y:0},camps,{steps:8,time:early});assert.deepEqual([...result.route].map(v=>v.type),['Chicken']);
result=c.erRecommendHunt({x:0,y:0},camps,{steps:8,time:night});assert.deepEqual([...result.route].map(v=>v.type).sort(),['AttackDrone','Bear','Chicken']);
assert(result.route.every(v=>c.erHuntAvailable(v,night)),'recommendation uses the same availability rule as the map');
camps[0].cleared=true;result=c.erRecommendHunt({x:0,y:0},camps,{time:early});assert.equal(result.route.length,0);
result=c.erRecommendHunt({x:0,y:0},camps,{time:night,blocked:['a']});assert.equal(result.route.length,0);
const clean=c.erHuntTime({day:Infinity,remaining:-70,phase:'invalid',survivors:'true'});assert.equal(clean.day,1);assert.equal(clean.remaining,0);assert.equal(clean.phase,'day');assert.equal(clean.survivors,false);
console.log('PASS: spawn countdown boundaries, day/night assumptions, map/recommendation consistency, exclusions');
