const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
(async () => {
    let requests = 0;
    const ctx = vm.createContext({console, fetch: async () => { requests++; return {ok: true, json: async () => ({data: [{code: 1, itemGrade: 'Rare'}]})}; }});
    vm.runInContext(fs.readFileSync('src/main/resources/static/js/fetchWeaponBgImg.js', 'utf8'), ctx);
    await Promise.all(Array.from({length: 100}, () => ctx.fetchWeaponAndArmorBgImg(1, 'weapon')));
    assert.equal(requests, 1, 'Concurrent equipment lookups share one HTTP request');
    const events = {};
    const detail = vm.createContext({document: {addEventListener: (n, f) => {events[n] = f;}}});
    vm.runInContext(fs.readFileSync('src/main/resources/static/js/matchDetails.js', 'utf8'), detail);
    let calls = 0;
    detail.loader = async () => { calls++; return '<p>경기 상세</p>'; };
    vm.runInContext("matchDetailLoaders.set('123', loader)", detail);
    const panel = {hidden: true, dataset: {}, classList: {contains: () => true}};
    const card = {dataset: {gameId: '123'}, nextElementSibling: panel, setAttribute() {}, querySelector: () => null};
    assert.equal(calls, 0);
    await detail.toggleMatchDetails(card);
    assert.equal(panel.innerHTML, '<p>경기 상세</p>');
    await detail.toggleMatchDetails(card);
    await detail.toggleMatchDetails(card);
    assert.equal(calls, 1, 'Reopening uses rendered detail cache');
    const explorer = vm.createContext({});
    vm.runInContext(fs.readFileSync('src/main/resources/static/js/explorer.js', 'utf8'), explorer);
    assert.equal(explorer.erEscape('<script>'), '&lt;script&gt;');
    assert.equal(explorer.erNames('Item/Name/1┃검').get('Item/Name/1'), '검');
    console.log('PASS: 100 equipment lookups => 1 request; lazy detail cache; safe rendering; localization');
})().catch(error => { console.error(error); process.exitCode = 1; });
