const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c=vm.createContext({document:{addEventListener(){}},erAssetBase:'https://example.test/'});
for(const f of ['siteData','weaponMetadata','player'])vm.runInContext(fs.readFileSync('src/main/resources/static/js/'+f+'.js','utf8'),c);
const own={nickname:'me',characterNum:1,teamNumber:1,killDetails:'{"2":2,"3":1}',deathDetails:'{"2":1}'};
const enemy={nickname:'enemy',characterNum:2,teamNumber:2};
assert(c.erCombatBadges(enemy,[own,enemy],own).includes('combat-kill'));
assert(c.erCombatBadges(enemy,[own,enemy],own).includes('combat-death'));
assert.equal(c.erCombatBadges(enemy,[own,enemy,{...enemy,nickname:'duplicate',teamNumber:3}],own),'');
assert.equal(c.erCombatBadges({...enemy,teamNumber:1},[own,enemy],own),'');
assert(c.erCombatBadges({...enemy,killer:'player',killDetail:'me'},[own,enemy,{...enemy}],own).includes('combat-kill'));
assert.equal(c.erPremadeBadge({preMade:1},[{preMade:1},{preMade:1},{preMade:1}]),'');
assert(c.erPremadeBadge({preMade:2},[{preMade:2},{preMade:2},{preMade:1}]).includes('2인'));
assert.equal(c.erPremadeBadge({preMade:2},[{preMade:2},{preMade:2},{preMade:2}]),'');
assert(c.erPremadeBadge({preMade:3},[{preMade:3},{preMade:3},{preMade:3}]).includes('3인'));
const stats=[{characterCode:1,usages:2,wins:1}];
const metrics={'1':{games:2,kills:8,killGames:2,teamKills:20,teamKillGames:2,damage:30000,damageGames:2,rp:15,rpGames:2}};
const html=c.erCharacterStatsTable(stats,metrics,'complete');
assert(html.includes('15,000'));assert(html.includes('K 4'));assert(html.includes('+15'));assert(html.includes('시즌'));
assert(c.erCharacterStatsTable([{...stats[0],usages:10}],metrics).includes('2/10전'));
assert(!/NaN|undefined/.test(c.erCharacterStatsTable(stats,{},'collecting')));
metrics['1'].killGames=1;assert(c.erCharacterStatsTable(stats,metrics).includes('K —'));
console.log('PASS: verified party sizes, ambiguous character suppression, two-way kill marks, seasonal/partial metrics and missing values');

assert(c.erMatchRank({matchingMode:3,mmrBefore:3177,mmrAfter:3220}).includes('3,177 RP'));
assert(c.erMatchRank({matchingMode:3,mmrBefore:3177}).includes('골드 II'));
assert(c.erMatchRank({matchingMode:3,mmrBefore:9000,gameRank:1}).includes('미스릴 이상'));
assert.equal(c.erMatchRank({matchingMode:2,mmrBefore:3177}), '');
assert.equal(c.erMatchRank({matchingMode:3}), '');
